import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import NotificationProvider from "./components/notifications/NotificationProvider";
import FloatingToasts from "./components/notifications/FloatingToasts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Next.js App Router generates exactly ONE <meta name="viewport"> from this export.
// viewportFit:"cover" extends layout behind notch + home bar on iOS Safari.
export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <NotificationProvider>
            {children}
            <FloatingToasts />
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
