import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import NotificationProvider from "./components/notifications/NotificationProvider";
import FloatingToasts from "./components/notifications/FloatingToasts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// viewport-fit=cover injected manually in <head> below to guarantee
// it appears in the rendered HTML — Next.js API can silently drop it.

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Must be the ONE viewport meta — viewport-fit=cover extends layout into notch/home-bar on iOS */}
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <NotificationProvider>
            {children}
            <FloatingToasts />
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
